version: "3.8"

services:
  nodejs-argo:
    image: ly920907/nodejs:empty
    container_name: nodejs-argo
    restart: always
    ports:
      - "3000:3000"
    environment:
      - SUB_PATH = sub  #订阅路径
      - UUID = xx
      - WS_PATH_BASE = /api/v1 #ws固定路径
      - WS_PATH_LEN = 8  #ws随机路径长度
      - ARGO_AUTH = ey  #隧道token
      - ARGO_PORT = 8001 #隧道端口
      - ARGO_DOMAIN = domain #隧道域名
      - CFIP = www.visa.cn #优选ip/域名
      - CFPORT = 443 #端口
      - NAME = vless-argo #名称
      - KOMARI_ENDPOINT = https://komari #komari面板
      - KOMARI_TOKEN =xx #komari-token
    network_mode: host     # 使用宿主机网络

