version: "3.8"

services:
  nodejs-argo:
    image: ly920907/nodejs:empty
    container_name: nodejs-argo
    restart: always
    ports:
      - "3000:3000"
    environment:
      - ARGO_AUTH=ey
    network_mode: host     # 使用宿主机网络

